spring:
  application:
    name: task_hayot
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/hayot_db
    hikari:
      pool-name: 'billing'
      max-lifetime: 1_800_000 # 30 minutes
      idle-timeout: 300_000 # Reduced to 5 minutes
      minimum-idle: 5 # Reduced to maintain fewer idle connections
      maximum-pool-size: 5 # Reduced to prevent reaching max_connections
      connection-timeout: 30_000 # 30 seconds
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8081

cors:
  allowedHeaders: [ "Accept", "Accept-Language", "Origin", "Content-Language", "Content-Type", "X-Requested-With", "Authorization" ]
  allowedOrigins: [ "*" ]
  allowedMethods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD" ]
  allowCredentials: false
  exposedHeaders: [ "X-Total-Count", "Content-Disposition" ]
  urlPattern: "/**"