version: '3.9'

services:
  postgres:
    container_name: postgres_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hayot_db
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
volumes:
  postgres_data: { }